name: Coverage Status

on:
  push:
    branches:
      - '**'

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm i -f
        env:
          NPM_TOKEN: ${{ secrets.npm_token }}

      - name: Run coverage
        run: npm run test:coverage
       
        